name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: install backend dependencies
        working-directory: ./puhelinluettelo_backend
        run: npm install

      - name: lint server
        working-directory: ./puhelinluettelo_backend
        run: npm run lint

      - name: build client
        working-directory: ./puhelinluettelo
        run: | 
          npm ci
          npm run build
          cp -r build ../puhelinluettelo_backend
        
      #- name: Bump version and push tag
      #  if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
      ##  uses: anothrNick/github-tag-action@1.33.0
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    DEFAULT_BUMP: patch

      - name: Deploy to heroku
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vanhanajanpuhelinkirja" 
          heroku_email: "teemu.varsala@hotmail.com"
          procfile: "web: node index.js"
          #branch: "master"
          appdir: "puhelinluettelo_backend  "
          rollbackonhealthcheckfailed: true
          healthcheck: "https://vanhanajanpuhelinkirja.herokuapp.com/api/healthcheck"
        env:
          VERSION: ${{ github.run_number}}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          